---
ip: "192.168.10.10"
memory: 2048
cpus: 2
provider: virtualbox
version: 8.0.1
ssl: true

authorize: {{ HC.RSA_KEY }}.pub

keys:
    - {{ HC.RSA_KEY }}

folders:
    - map: {{ HC.SOURCE_DIRECTORY }}
      to: /home/vagrant/hackcambridge

sites:
    - map: hackcambridge.test
      to: /home/vagrant/hackcambridge/public

databases:
    - homestead